version: "{build}"

environment:
  global:
    HAXELIB_ROOT: C:\projects\haxelib

install:
  - ps: Set-Service wuauserv -StartupType Manual
  - cinst neko --version 2.3.0 -y
  - cinst haxe --version 4.2.3 -y
  - RefreshEnv
  - mkdir "%HAXELIB_ROOT%"
  - haxelib setup "%HAXELIB_ROOT%"
  - haxelib install lime 7.9.0
  - RefreshEnv
  - haxelib install openfl
  - haxelib install flixel
  - haxelib run lime setup flixel
  - haxelib run lime setup
  - haxelib install flixel-tools
  - haxelib install flixel-addons
  - haxelib install flixel-ui
  - haxelib install hscript
  - haxelib install flixel-addons
  - haxelib git faxe https://github.com/uhrobots/faxe
  - haxelib git polymod https://github.com/larsiusprime/polymod.git
  - haxelib git discord_rpc https://github.com/Aidan63/linc_discord-rpc
  - haxelib git HxCodec https://github.com/KadeDev/extension-webm
  - haxelib git linc_luajit https://github.com/nebulazorua/linc_luajit.git
  - haxelib git hxvm-luajit https://github.com/nebulazorua/hxvm-luajit
  - haxelib git hxCodec https://github.com/polybiusproxy/hxCodec
  - haxelib install actuate 
  - haxelib list

build_script:
  - haxelib run lime build windows

artifacts:
  - path: export/release/windows/bin
    name: Reanimated-Windows
    type: zip
